### PR TITLE
Reorganize ethtool command to get link speed and add support for new ethtool command

### PR DESCRIPTION
**Pull request by gospo**

### CODE REVIEW

**Comment by sflow** [comment]
I get this error when I try to compile with these changes on Red Hat 5.10 or Ubuntu 14.04:

readInterfaces.c:268:32: error: field ‘base’ has incomplete type
   struct ethtool_link_settings base;

**Comment by gospo** [comment]
Gah!  I needed to wrap the new definitions for ethtool_link_usettings and friends around ETHTOOL_GLINKSETTINGS since it was included in the same upstream commit.  I'll rebase.

**Comment by gospo** [comment]
I updated the last commit and pushed a new repo, so this pull request should still be valid, but have updated code.  This should resolve the issue you are seeing when compiling on older kernels.

**Comment by sflow** [comment]
This was still failing to compile with "make OPTICAL_STATS=yes",  however I included your ETHTOOL_GLINKSETTINGS code in the latest commit on "master",  where the ethtool commands in readInterfaces.c are broken out more.  Please try it there.   The 1.0 code is still accessible in branch "hsflowd-1".

**Comment by gospo** [comment]
Ok, I'll check it out.
